---
title: "Overview"
output: html_document
---
<style type="text/css">

h1.title {

text-align: center;
color: DarkBlue;
font-size: 38px;

}

p{

font-size: 18pt;
font-family: times, serif;
}

p1{

font-size: 14pt;
font-family: times, serif;
}

</style>

<p>
  Living cells can be described as a collection of complex dynamical systems that are responsible for constantly reconfiguring the cell's characater in response to environmental stimuli. Gene regulatory networks (GRN’s) are one such type of dynamical system and are the focus of GeneEx, the webtool we highlight in this tutorial. GRN’s are most precisely described as an assembly of interacting transcription factors and other molecular regulators that control the gene expression levels for a given biological process. GRN’s have become a major area of study since changes in gene expression or network topology have been shown to drive a number of biological phenomena such as population heterogeneity, disease emergence, and the evolution of morphological novelties.  Moreover, GRN’s have been shown to be a useful tool for investigating a number of biological challenges such as the derivation of novel hypotheses about molecular interactions, elucidation of potential targets for drug design, and comparative analysis between different physiological or disease conditions.
</p>

<p>
 Systems biology aims to understand how GRN’s and other dynamical systems function and cooperate by using a variety of modeling schemes to systematically perturb them. Mathematical modeling, the process of translating a biological relationship into a mathematical formulation, has witnessed a recent surge in popularity since obtaining complete operational pictures of GRN’s, using solely experimental approaches, has proven exigent. Consequently, a variety of unique computational approaches have been developed to model the dynamics of GRN’s such as Boolean network models, ordinary differential equations (ODEs)-based models, and Bayesian network models. This tutorial explores GeneEx, an interactive webtool we developed that uses an ODE-base mathematical modeling approach to simulate, visualize, and analyze GRN’s.
</p>

<!--<p style="font-family: times, serif; font-size:18pt;"> </p> -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

